### ISSUE TITLE
How to prevent multiple records

### ISSUE THREAD

**Issue by danielk1260** [aziev/jquery.fajax#1]
After the first submit is created 1 record, without refreshing the browser after the second submit 2 records are created and so on is creating a record more, maybe it can be resetonseccess?

**Comment by aziev** [comment]
Hi @danielk1260 

You can disable submit button after first submition like so:

```js
var $form = $('form');

$form.fajax({
    success: function () {
        $form.find('input[type=submit]').attr('disabled', true);
    },
});
```

**Comment by danielk1260** [comment]
thanks for the help, this script is amazing for designers. good work!
